### PR TITLE
Code tidying, etc

### PR DESCRIPTION
**Pull request by guacaplushy**
I’ll try to update more when i get the chance

### CODE REVIEW

**Comment by JeffJrShim** [comment]
Please inform when you are done.

**Comment by guacaplushy** [comment]
I’ll do it in another PR, so this one should be done

**Comment by JeffJrShim** [comment]
Please resolve the conflict.

**Review by JeffJrShim — APPROVED** [review]
These are fine, LGTM

**Review by JeffJrShim — CHANGES_REQUESTED** [review]
Please fix all conflicts, so i can merge them

**Comment by guacaplushy** [comment]
a

**Review by JeffJrShim — APPROVED** [review]
LGTM

**Pull request merged**
